calls:
- max_evals: 25
  timeout: null
- max_evals: 5
  timeout: null
search:
  acq_func: UCBd
  acq_optimizer: auto
  acq_optimizer_freq: 10
  evaluator:
    num_workers: 1
    type: RayEvaluator
  filter_duplicated: true
  filter_failures: min
  initial_point_generator: random
  initial_points:
  - activation: relu
    batch_size: 32
    dropout_rate: 0.5
    learning_rate: 0.001
    num_epochs: 50
    units: 32
  kappa: 1.96
  kwargs: {}
  log_dir: .
  max_failures: 100
  moo_lower_bounds: null
  moo_scalarization_strategy: Chebyshev
  moo_scalarization_weight: null
  multi_point_strategy: cl_max
  n_initial_points: 10
  n_jobs: 1
  n_points: 10000
  objective_scaler: auto
  problem:
    conditions: []
    forbiddens: []
    hyperparameters:
    - choices:
      - elu
      - gelu
      - hard_sigmoid
      - linear
      - relu
      - selu
      - sigmoid
      - softplus
      - softsign
      - swish
      - tanh
      default: relu
      name: activation
      type: categorical
      weights: null
    - default: 32
      log: true
      lower: 8
      name: batch_size
      q: null
      type: uniform_int
      upper: 256
    - default: 0.5
      log: false
      lower: 0.0
      name: dropout_rate
      q: null
      type: uniform_float
      upper: 0.6
    - default: 0.001
      log: true
      lower: 1.0e-05
      name: learning_rate
      q: null
      type: uniform_float
      upper: 0.01
    - default: 50
      log: false
      lower: 10
      name: num_epochs
      q: null
      type: uniform_int
      upper: 100
    - default: 32
      log: false
      lower: 8
      name: units
      q: null
      type: uniform_int
      upper: 128
    json_format_version: 0.4
    python_module_version: 0.6.1
  random_state: null
  scheduler: null
  stopper: null
  surrogate_model: ET
  surrogate_model_kwargs: null
  sync_communication: false
  type: CBO
  update_prior: false
  update_prior_quantile: 0.1
  verbose: 0
  xi: 0.001
